# Generated by Django 4.2.11 on 2024-03-29 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_profesor_alumno_curso_profesor_de_la_catedra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='profesor_de_la_catedra',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cursos', to='AppCoder.profesor'),
        ),
    ]
