# Generated by Django 4.2.11 on 2024-03-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_alter_curso_profesor_de_la_catedra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='curso',
        ),
        migrations.AddField(
            model_name='alumno',
            name='curso',
            field=models.ManyToManyField(related_name='Alumnos', to='AppCoder.curso'),
        ),
    ]
